/* عدّل البيانات هنا فقط */
const CONFIG={eventDate:"2026-12-31T20:00:00",eventDateArabic:"31 ديسمبر 2026 · الساعة 8:00 مساءً",mapsUrl:"https://maps.app.goo.gl/uzpyK4hZpvjFcDH76",googleAppsScriptUrl:"",eventDurationMinutes:180};
addEventListener("DOMContentLoaded",()=>{document.getElementById("heroDate").textContent=CONFIG.eventDateArabic;document.getElementById("eventDateText").textContent=CONFIG.eventDateArabic;document.getElementById("mapsBtn").href=CONFIG.mapsUrl;if(window.AOS)AOS.init({once:true,duration:850,easing:"ease-out-cubic",offset:60});countdown();music();calendar();share();rsvp();setTimeout(()=>document.getElementById("loader").classList.add("hidden"),500)});
function countdown(){const t=new Date(CONFIG.eventDate).getTime();function u(){let d=t-Date.now();if(d<0)d=0;document.getElementById("days").textContent=String(Math.floor(d/864e5)).padStart(2,"0");document.getElementById("hours").textContent=String(Math.floor(d%864e5/36e5)).padStart(2,"0");document.getElementById("minutes").textContent=String(Math.floor(d%36e5/6e4)).padStart(2,"0");document.getElementById("seconds").textContent=String(Math.floor(d%6e4/1e3)).padStart(2,"0")}u();setInterval(u,1000)}
function music(){const a=document.getElementById("bgMusic"),b=document.getElementById("musicBtn");b.onclick=async()=>{try{if(a.paused){await a.play();b.classList.add("playing")}else{a.pause();b.classList.remove("playing")}}catch{toast("اضغط مرة أخرى لتشغيل الموسيقى")}}}
function calendar(){document.getElementById("calendarBtn").onclick=()=>{const s=new Date(CONFIG.eventDate),e=new Date(s.getTime()+CONFIG.eventDurationMinutes*6e4),f=x=>x.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"");const u=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent("MYRIAM & AHMED — Wedding")}&dates=${f(s)}/${f(e)}&details=${encodeURIComponent("Wedding invitation — Myriam & Ahmed")}&location=${encodeURIComponent("Saladin Citadel, Cairo")}`;open(u,"_blank")}}
function share(){document.getElementById("shareBtn").onclick=async()=>{if(navigator.share){try{await navigator.share({title:"MYRIAM & AHMED",text:"دعوة زفاف Myriam & Ahmed",url:location.href})}catch{}}else copy()};document.getElementById("copyBtn").onclick=copy}async function copy(){try{await navigator.clipboard.writeText(location.href);toast("تم نسخ رابط الدعوة")}catch{toast("انسخ الرابط من المتصفح")}}
function rsvp(){document.getElementById("rsvpForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=document.getElementById("formStatus"),data=Object.fromEntries(new FormData(f));if(!CONFIG.googleAppsScriptUrl){s.textContent="تم تسجيل البيانات تجريبيًا. اربط Google Apps Script للحفظ الفعلي.";f.reset();toast("تم إرسال تأكيد الحضور");return}s.textContent="جاري الإرسال…";try{await fetch(CONFIG.googleAppsScriptUrl,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});f.reset();s.textContent="شكرًا لك. تم إرسال تأكيد الحضور.";toast("تم إرسال تأكيد الحضور")}catch{s.textContent="حدث خطأ. حاول مرة أخرى."}}}
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
